language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t samcdonovan/docker-react-CI -f Dockerfile.dev .

script:
  - docker run -e CI=true samcdonovan/docker-react-CI npm run test
